annotations:
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 2.4.5
dependencies:
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.x.x
  condition: ingress-nginx.enabled
- name: cert-manager
  repository: https://charts.jetstack.io
  version: 1.x.x
  condition: cert-manager.enabled
- name: uffizzi-cluster-operator
  repository: https://uffizzicloud.github.io/uffizzi-cluster-operator/
  version: 1.6.5
  condition: uffizzi-cluster-operator.enabled
description: A smart proxy service that handles requests from Uffizzi App to the Kubernetes
  API - 1 of 3 services (controller, uffizzi_app, uffizzi_cli) that comprise the uffizzi
  full-stack previews engine which automates trigger-based on-demand preview environments
home: https://uffizzi.com/
icon: https://app.uffizzi.com/favicon.png
keywords:
- devops
- uffizzi
- continuous-previews
- ephemeral
- environments
- pull-request
- merge-request
- on-demand
- ci
- cd
- vclusters
kubeVersion: '>= 1.21.6-0'
maintainers:
- email: info@uffizzi.com
  name: Uffizzi
  url: https://uffizzi.com
- email: adam.vollrath@uffizzi.com
  name: Adam Vollrath
  url: https://github.com/axisofentropy
name: uffizzi-controller
sources:
- https://github.com/UffizziCloud/uffizzi_controller
- https://gitlab.com/dualbootpartners/idyl/uffizzi_controller
type: application
version: 2.4.6
