#!/bin/bash

# --- PARAMETERS (Arguments or Defaults) ---
# $1 is the first argument (Endpoint URL)
# $2 is the second argument (Function Name)
ENDPOINT_URL="${1:-http://brossi.dev.ministack.local}"
FUNCTION_NAME="${2:-mia-funzione-brossi}"

RUNTIME="python3.9"
ROLE="arn:aws:iam::000000000000:role/lambda-ex"
HANDLER="index.handler"

# Input payload variables
PAYLOAD_INPUT='{"user": "Brossi", "status": "testing", "message": "Hello from k3s input"}'

echo "📌 Using Endpoint URL: $ENDPOINT_URL"
echo "📌 Using Function Name: $FUNCTION_NAME"
echo "--------------------------------------------------"

# 1. EXPORT MOCK ENVIRONMENT VARIABLES FOR AWS CLI
echo "🔑 Configuring AWS environment variables..."
export AWS_ACCESS_KEY_ID="mock-key"
export AWS_SECRET_ACCESS_KEY="mock-secret"
export AWS_DEFAULT_REGION="us-east-1"

# 2. CREATE LAMBDA SOURCE CODE
echo "📝 Creating Lambda source code..."
cat << 'EOF' > index.py
import json

def handler(event, context):
    print("Received event: " + json.dumps(event))
    username = event.get('user', 'Unknown')
    status = event.get('status', 'none')
    
    return {
        'statusCode': 200,
        'body': f"Hello {username}! Your status is '{status}'. Successfully processed inside k3s!"
    }
EOF

# 3. CREATE ZIP PACKAGE
echo "📦 Creating ZIP package..."
zip -q function.zip index.py

# 4. DEPLOY LAMBDA TO MINISTACK
echo "🚀 Deploying Lambda to MiniStack ($ENDPOINT_URL)..."
aws lambda delete-function --endpoint-url=$ENDPOINT_URL --function-name $FUNCTION_NAME 2>/dev/null

aws lambda create-function \
    --endpoint-url=$ENDPOINT_URL \
    --function-name $FUNCTION_NAME \
    --runtime $RUNTIME \
    --role $ROLE \
    --handler $HANDLER \
    --zip-file fileb://function.zip

# 5. EXPOSE LAMBDA URL (FUNCTION URL)
echo "🌐 Generating Function URL..."
# We append a / to make sure create-function-url-config works if needed
FUNCTION_URL_JSON=$(aws lambda create-function-url-config \
    --endpoint-url=$ENDPOINT_URL \
    --function-name $FUNCTION_NAME \
    --auth-type NONE 2>/dev/null)

if [ -n "$FUNCTION_URL_JSON" ] && command -v jq &> /dev/null; then
    GENERATED_URL=$(echo "$FUNCTION_URL_JSON" | jq -r '.FunctionUrl')
    echo "🔗 URL Generated by MiniStack: $GENERATED_URL"
else
    echo "⚠️ Continuing without parsing Function URL JSON..."
fi

# 6. INVOCATION VIA AWS CLI
echo "🎯 Invoking Lambda via AWS CLI with input variables..."
aws lambda invoke \
    --endpoint-url=$ENDPOINT_URL \
    --function-name $FUNCTION_NAME \
    --payload "$PAYLOAD_INPUT" \
    --cli-binary-format raw-in-base64-out \
    output.json

echo "📄 AWS CLI Response:"
cat output.json
echo ""

# 7. INVOCATION VIA CURL (HTTP)
echo "🌐 Direct invocation via HTTP endpoint with input variables..."
echo "Running curl..."
curl -s -X POST "$ENDPOINT_URL/2021-11-01/functions/$FUNCTION_NAME/invocations" \
    -d "$PAYLOAD_INPUT"
echo ""

# Clean up local temporary files
rm -f index.py function.zip output.json

echo "✅ Process completed! Script reached the end successfully."

