---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uffizzi-controller
  namespace: eph-env
spec:
  encryptedData:
    password: AgAzILSTWHwSIXQAGw82VA1h3NYq35C5gJBGPUA57BZWgHZ+1su1DpE1qVhA1OoN2pt0AT1FprpL1o4ztVgEna43Grs06DXqFh2yvyAiN2hoCME98yfuhYJYNX/FOmxpXMHk1ibEZGDlED7Lm/At4cy+Y4Ln9YCAy4YhX0XOWXAzcumwDqHsQpGUupyVqpwrz9gfLyYE/kpa2QmU2IdgkzFhbd4C7Z9uZ++ssisYiD068IusF8sqGaQHaIVY772kA4/oJHk1hkr4RVIoJ5S0KoHEQrskjrZUms0iIU77Qt3AGvTiZ+qpUHOS9IZcaafDWzA4bP+9tETOQJ52ug3Gd3t56b+H+6xmPEZsrRAEHty5YUsN+NppYzcEuJKQ+x8KBz3HFOu97EdmRycE08xDrkUzctC6lFtaYbnSuspm/hrpsIGYVq+ifkADhhGN2uvcgADdEDa/fsknCHnFSdZG+tX17t0eNSJmvFz3IHt/Hru5DgtEmrpgLKWbAvgUyj6NifQw2oIdAbrPTtvZ5Ud8qaPFXUCSTtbPhHU7WcvZp8hrHsXwagtexgFa1MBRr7a3XVmoTSawio2Y8e4klDaXsof42rz03TK01fxOZ0ctET+CxGBSGJv12yxSuIoW6vbMV70iCRRiXskF7u9TUIoIKnQNFdCU/dOmhDD/IEhAS+k9WoXUzafvHHCL0WIRpv4oJ65vGewRCSWiA0Au
    username: AgB3BfkzxwDHzgEsSZEAVss5CyGWla9PmQw+3t8dXODdZBa5uQIYwS9dBVD7DmoTbq00qOGJZHO9NHVs/0LaUzx08k/3rawg2hkHK0iRA7sssaL/cyKsYun/NNMGHpS/Xl8/j6xLHilro+xz2Pc4rcLMsdGV3IzI/Ep31x3tu6NZBEXMAPJ+hv7ks6rMsAyNYAAmgyKaFJAcm3amdO9e2gXdFtawaUB8Vt/c8YAjt3PNpx6y61VNmH4Iy7CSNgLsS1my/+f0iOyco4mhNP9iOrF+azBhR4dg7lTG90JmcJn6n3N5HI7vOGo3N60oGjoTmQyRTGtrMnTCyN7SbEte9DvjZ7X/rIM8SmZOGeDS474wCoKx294kmykJyTsRdJG/Girk5y2USVGkKBeamNkbEpdQ9icwLeqYS7usjLThe3IwLdaw1a/ESVMnFTPksVJ7/aJvGnhyipP7dkElFqs3YYB5pSrP2TG0slPOSFkE0hrVD+sph9xXD7b0i59r0uiEAZv8lCLXECM6nam+wFHlwpHSKpEYU8n/Ned8ALU+TItKbMqU5NOzsLyIjh1TtbKGRSDSJkc3aRHrOPHttwblsWkUP6X6Q/BQm4HsWLoCsxNp78NADHX0JBWg0ac04yjc+e8G8SN2T0L7mfTWkQMweGPi5v5yuQzBV/PDeOytZzrdXsrvO/Oj8urD1zkad+j/4T0xTkTf5/AF2JP4A4DDhYBPaa4=
  template:
    metadata:
      name: uffizzi-controller
      namespace: eph-env
