---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uffizzi-first-user
  namespace: eph-env
spec:
  encryptedData:
    email: AgCz0yVH3vIEGwakVGK7wqHynBX39J9EE4YriC0KIKh86mN145SJcnGzKDVULw1WUyXd10x63gmQjOOLcL9aRK9wEYa1Hc3HVt5lPjfkA4ToKRwlD7e/jaZ2C8fgoHqKKoMhjejEJNRe0zq5wmc9Ha/s1rcJQEEHOqdWjO8RJ8JKsTonmcyY/CcDHoSe85r67Z2wrFnJ0zcd4nYrmOcKIo4zcmpQuN/sSWLEvmGe++MTZcNq7kaU3mzZn/bBS++mFhIiZQdHqO+tP9UK5rH79wxx0WaQac080dFh2AuKWzbPMm+Utrt5yPf+pomyR5JdyhtNlootSUdbE7I2cDl3e5UrIaJbMkCopOfCdND+5njYZSkOUmarsn+4o0IPyq4tNVDqV8qlzGMPuv6pnZ5kHkORY9/QiK33biIR1tjWlZ1D261CDH6PXqxqlrT8qU6M9efRSPTXRgpwmpxcSCdxWRMeNDbHHwN979SXq0Sb2w4CSz5b0kbahFSO1mdjrox52jMPD1xqoxtKgdL0kYpbNBjac7PbOmWbkCfyEBuJLcCzvj0mOea9/2xGtUCwpx9HSMC3kCHSxbCcHk3B4q/AvhPOrZ2S95ABtXAVaKDoXCdD/7NKixIMSzdzR/bMGjX0Zjph7kN6as/M9ERyeqNDj5/F5AZm+ut/Zc5zF5NTNzS9nKOB3yP9yuiHtv8G+n300Hk4VFhF7sRB7BGlvDJoz1Kc+hO1kak=
    password: AgBLSqP2KpGIxfS+9IQ0XvwZ/rYPCQh1kh+WMHbbGeoET/85rVwmgSnyGZBx692We4gj5/JDga/fzhKu7Wit5wgbpKloPhY2vRhnEO9eZdZ4mcRgmGXd9EiH5uSvEKu3cMLTQRmU5Jj2YzMMSkp50SGANuoswTrQfhIWZALl25RsaB9wur69tGezqE24XwLLcD6yc1BwDtG5ESAnBv6RlJyn27dXUX3tLPOLXZJOxfVhIaKmAoW5cn2dpy8JCYiALemBmDiER3p4cEwshb0ImmrPhXLFBoH3SK7AH42nL2j7D6EimFFxBUBTAagu+HDoleMWV3HyrFvJ8+C80rvKFdx/ZRVWAGg5tmWEI9npE/aWJIhFSeRKbpuc7eGdo5VtxvG6R7rhu8Gg41GpkqsS7+KbiLpMJ7gcjL14wuh9VZW6St9Fe9Gik81aHeRMd1nGgVcvvXUBIhToSM0YLu5TFqXgpKmvCJJfr6tI++ICiCTpQ6k3A44GJcTwwcMDfrfAut2G2QkBOKKNykZ1CcE3Jc4MtH1Rb4ATU1NH+M2lvdV/51DFnmT/9QTe7YBt2I1HXnmHUdwJES+gpDpOWh50wMWIJrlZdvLZuV977TLB7270VbbmkKDZ09S+1cN5WoymRvzFUxBgL29YEeqy4gkfvzZ+eHow/7kOUQmJPp4Glu6gzYHK4SiAocNpabuY9q/n+bEfdSN55F99zlkN
  template:
    metadata:
      name: uffizzi-first-user
      namespace: eph-env
