---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uffizzi-controller-env
  namespace: eph-env
spec:
  encryptedData:
    CONTROLLER_LOGIN: AgCrB1x0pH8dUep6UWwUMy/B4MmRUweXdj5XbguD60t8+YBta7jHiRj2pQyKjHgOguVDl0ufcXYx/F8HNtvfVYN1MMnxEWlhNLYj6KYbwtIuKELb6WQKRQOE5mhue9QdLDImilvH9r8NmyKGO1FejOESZX8rQ7TI3SeOHLVTO50t6ievlZc94IKq6EAPDmpUl+pLC9Uc72ycvyCa7UOvfbjnLF3tAjR9OAMpmdrFSPGE6h0Hughssg6aydl1ifFvxziw1k4HRDbjNRlay7qU4KbVDD5PJqTZ1/ywSmtOGNk4EHOjnL0f/kl2gxGC4svaf3O8YAnjdhdkZrZXC7MzwgdCGb5tYKqck2j4VJOxI1509alBELFztaG2rOH79OzLbgpseAo61wfVDGbA1Jwqd32auHafK915ZDBM2VuwrIU8uZ8l9sQ7cWfu1KEZortBNM/hwNQ3kOrNLhRdcdnIgXYx/cpuXlKgoAm5AmFccaGgjgtF0TIfp04XklZAPyw3xOxm9/FQCsTfhAc008mYvKFCnpuZGYZBfE0u2YibguGkUPsX4giACUn8Cu12OpG0znM7IpDVIHQC/u055bR1kpr6+OTGW9QGrnlSyQTuFEvDzvusnkRY52lUTcJTJzIBOpkisN1IOMv/qfSwFXko7iz3NA/APnSl6XEZknkZMq7c7nJlUue8taGRu74YIf8GS9eoSzaZEh741Dn7ARbq75Gsc04=
    CONTROLLER_PASSWORD: AgA4nNqQPlNko5k5wHiwojD4dXVKaJZ/wQHv5i8AB5D5QmUDOEknpgDR1VGjMnwl4shSFhLUvyAW2VopBnSjn58xF4ycHVSBl2rUxh6H+Z/F7SPWBlv1m9H6XAHE6EO3hmFdxDAwjTQ6Jyjs7tralgrwqBaK8lrsgmzaiUcoouisUgwdKwXOdXhn3dq9O1Ic5XkBEMfl0IIF1bgnB5uOnVOrWC0jjYWXfi7vq1K3iazkXMJuODiNFPdynj3dFZcM5XoOJA8hUZ5aD0ZKzIrTSIrJ3I8Svj7IVnHjoNa5GOTRB668eYrkb+9M0rR9IAigJ+GUexm8xGWi1KVW787eLyPbftV6lJe2WjYLVq+XFjNr5p0JRwh/a5O/bzBEfmH6kp4/XYhPqH+7yVzFWTy5WOvCoaGjK6/W8Ngf54waStUzqyCNi5ZWOPkLmWJF0U1C0YsWWAS6DH+rng3eB1VcjO2NWdnY8q5w5oDFj6nAQWQtUIEwLj6En9ObfGiXQzf8fPhlg+gfN/dkLl2HRvSZ39a2s4DGPD0Tn5qA+eLtui+Z72Ih3L8Uq3smS/JpMYcU+Vm2w/MSu6K2GLGmO15F3oEWk0ayWDGDSm8VMpBqt1EG8ont3tHiTWmWuD4FqpHLhmtdqdkLfxzsThYTK5z0S/3Xo1ajAHQRmgMaEuhF3ZIN3sW3/AdZYhp85T/TQ50CqAZbvdZDQ2wf9JPr
  template:
    metadata:
      name: uffizzi-controller-env
      namespace: eph-env
